### PR TITLE
GPU aware MPI fixes

### PR DESCRIPTION
**Pull request by awnawab**
I discovered strange unaligned memory access issues with GPU aware MPI for small partition sizes. These were resolved by packing the 8 MPI exchanges in `PROENVHALO` into one. I also added support for single precision builds for GPU aware MPI and updated to F2008 bindings.

I have done the usual round of coupled testing, this time also with ecWAM on GPU. CPU only performance was also confirmed as unaffected using standalone O1280 runs.

### CODE REVIEW

**Comment by awnawab** [comment]
Hi @jrbidlot. Could you also please review these changes? I saw that there was already a comment in the code suggesting the MPI exchanges should be merged into one.

**Review by jrbidlot — APPROVED** [review]
Hi Ahmad,

it looks all very sensible.

**Review by jrbidlot — APPROVED** [review]
It seems OK.

**Review by wdeconinck — APPROVED** [review]
Great! Thanks @awnawab !!

**Pull request merged**
