### PR TITLE
Loki: Update loki config files to new format

### PR DESCRIPTION
**Pull request by mlange05**
Small update to the Loki configurations that is synced with the Scheduler update in Loki PR 191: https://github.com/ecmwf-ifs/loki/pull/191

### CODE REVIEW

**Comment by FussyDuck** [comment]
[CLA assistant check](https://bol-claassistant.ecmwf.int:443/ecmwf-ifs/ecwam?pullRequest=7) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://bol-claassistant.ecmwf.int:443/ecmwf-ifs/ecwam?pullRequest=7) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://bol-claassistant.ecmwf.int:443/check/ecmwf-ifs/ecwam?pullRequest=7) it.</sub>

**Review by awnawab — APPROVED** [review]
Thanks a lot for the heads-up and for filing this PR! 😄

**Comment by reuterbal** [comment]
I think this PR needs the CI fixes for Intel

**Comment by awnawab** [comment]
Thanks for flagging the Intel CI @reuterbal. It's now failing because of another (known) problem in my base branch. Please let me know when you are about to merge the corresponding Loki branch, I'll push a fix here and merge this one too.

**Pull request merged**
